// Generated by CoffeeScript 1.9.3
(function() {
  var assert, should, util;

  assert = require("assert");

  should = require('chai').should();

  util = require("../app/public/util");

  describe("util", function() {
    return it("util.root test", function() {
      util.root.should.a('string');
      return util.root.length.should.above(1);
    });
  });

  describe("mocha demo", function() {
    return it("mocha demo1", function() {
      2..should.a('number');
      return 4..should.above(1);
    });
  });

}).call(this);

//# sourceMappingURL=spider.js.map
