// Generated by CoffeeScript 1.9.3
(function() {
  requireb.config({
    urlArgs: {
      "scripts/*": "v=" + (new Date - 0)
    },
    paths: {
      "lib": "Content/libs",
      "sc": "Scripts",
      "pub": "scr/Public",
      "util": "public/util",
      "jquery": "content/libs/jquery-ui-1.10.4/js/jquery-1.10.2.js",
      "bootstrap": "content/libs/bootstrap/js/bootstrap.js",
      "app": "Scripts/Public/app2.js",
      "lodash": "content/libs/lodash/lodash.js"
    },
    shim: {
      bootstrap: {
        deps: ["jquery"],
        exports: '$'
      },
      app: {
        deps: ["bootstrap"],
        exports: '$'
      }
    }
  });

  requireb(["sc/index/main_index"], function(index) {
    return index.init();
  });

}).call(this);

//# sourceMappingURL=main.js.map
