// Generated by CoffeeScript 1.9.3
(function() {
  define(function() {
    var obj1;
    obj1 = {
      arg0: "arg0 obj1",
      arg1: "arg1 obj1"
    };
    return obj1;
  });

}).call(this);

//# sourceMappingURL=module1.js.map
