// Generated by CoffeeScript 1.9.3
(function() {
  define([], function() {
    var menu;
    menu = [];
    menu.push({
      name: "work",
      url: "",
      child: [
        {
          name: "directories",
          url: ""
        }, {
          name: "back",
          url: ""
        }
      ]
    });
    menu.push({
      name: "back",
      url: "",
      child: [{}]
    });
    return menu;
  });

}).call(this);

//# sourceMappingURL=menu.js.map
